# .travis.yml for Kitura Swift Packages

# whitelist
branches:
  only:
    - master
    - develop

notifications:
  slack:
    secure: "GJFQ3RigPnCyLWQvEoJdpEqkGMd4c+dxkRSLsrBksIDilRd6bPW6tcALat/HVvHecZBHWV8mDFHTkGwN/0aWe4YGh+W6DTgDcwGV2yE+r5TS0Sp7CVXyDBsSA8Lt79E4cReN+agrtFAkj5frB6+NeQwfTyP4p2+MFN0ii67aogCMbKqO+lAYO/ciz8b+dEv9QDivDZZF4B5QznrM5KZ0PK+PZ0StEvpALT8d85YPQSEH4LAdUD+oqtPi8JkeRt0X5cZ9iRaZ19MgqEXyiBh8PZ0UGyStMEgmNxHAJ80WCQYV2eHh88ESlbYdBn330aA+vojpUqPb+AJsBJko+j9B/EkZ8AVL8byDK0j8sUaKCC9TQCuStpXCqrhcJzPUggbmIG0oEl1+beHBUS/Z9Zk8WythiQQLd9aH5O1bvWFIOGXgw8KzL1ldKudQ+sp1ZxfC1oKnbR9IiyTA/jScdl7OoHa0vyakEtS0YhUlZgOCDKVkXK88sYuUu2ixq08Edfi3ShJdA27mhSnR5j7rs+feuAFTZN7XZEwVRsS4hGCXz1j/DsmOOMKxAH8eYxUkKu14viIOfwUAIqp6J8PrRrZkO2mTdCSZCZyl9iFWcxGDT5cZFjLsnWVgjuIlzXnrRJWJ5B1wABPUe/u8yGUYX+tUkF1g6H4rFJYEgdnaPDdQmoM="

matrix:
  include:
    - os: linux
      services: docker
      sudo: required
    - os: osx
      osx_image: xcode7.3
      sudo: required

before_install:
  - git submodule init
  - git submodule update
  - cd Kitura-Build && git checkout $TRAVIS_BRANCH && cd $TRAVIS_BUILD_DIR

script:
  - echo ">> Let's build and test the '$TRAVIS_BRANCH' branch for Kitura-sys."
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./Kitura-Build/run_kitura_ubuntu_container.sh $TRAVIS_BRANCH $TRAVIS_BUILD_DIR Kitura; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./Kitura-Build/build_kitura_package.sh ; fi
  - echo ">> Build and tests completed. See above for status."
